/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const path = require('path')
const merge = require("webpack-merge")
// Load config generated by scalajs-bundler
const config = require('./scalajs.webpack.config')
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');
const RootDir = path.resolve(__dirname, '../../../..')
const ResourcesDir = path.resolve(RootDir, 'src/main/resources')

module.exports = merge(config, {
    entry: {
        'index': path.resolve(ResourcesDir, 'index.js')
    },
    resolve: {
        modules: [path.resolve(__dirname, 'node_modules')]
    },
    module: {
        rules: [{
            test: /\.css$/,
            use: ['style-loader', 'css-loader']
        }, {
            test: /\.ttf$/,
            use: ['file-loader']
        }]
    },
    plugins: [
        new MonacoWebpackPlugin()
    ]
});
